version: '3.8'

services:
  coop-rest-java:
    container_name: coop-rest-bclan-${DOCKER_NETWORK}
    image: ${DOCKER_REPOSITORY}c2-sandbox-ssm-gateway:${VERSION_C2}
    ports:
      - "9090:9090"
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
